function Hd = WhisperLoPass
%WHISPERLOPASS Returns a discrete-time filter object.

%
% M-File generated by MATLAB(R) 7.3 and the Signal Processing Toolbox 6.6.
%
% Generated on: 26-Jun-2008 10:53:14
%

% FIR maximally flat Lowpass filter designed using the MAXFLAT function.

% All frequency values are in Hz.
Fs = 24000;  % Sampling Frequency

N  = 10;    % Order
Fc = 2000;  % Cutoff Frequency

%% Calculate the second-order sections coefficients to avoid round-off
%errors.
[b,a,b1,b2,sos_var,g] = maxflat(N, 'sym', Fc/(Fs/2));
Hd                    = dfilt.df2sos(sos_var, g);


% [EOF]
